### ISSUE TITLE
CIM Issues with ESXi 6.7 and Dell Openmanage

### ISSUE THREAD

**Issue by ucola** [Napsty/check_esxi_hardware#34] opened 2019-04-18 14:37 UTC
Hi all

Thank you for your work!
Our ESXi 6.7 works fine. But after some time we became this error

UNKNOWN: (0, 'Socket error: [Errno 104] Connection reset by peer')

Any ideas whats going wrong?

Thank you for your help

**Comment by Napsty** [comment] 2019-04-24 10:51
Please check the FAQ (https://www.claudiokuenzler.com/blog/308/check-esxi-hardware-faq-frequently-asked-questions) for potential reasons. This seems to be an issue of either network or the CIM server running on that ESXi host. Try to restart the relevant services (again, check the FAQ).

**Comment by ucola** [comment] 2019-04-25 08:30
thank you for your feedback! if i do
/sbin/services.sh restart

on esxi it works again... but I think after some time it will crash again... possible to do this with a crontab? or any better idea? thank you for your help

**Comment by Napsty** [comment] 2019-04-25 08:38
Yes, a cron job would probably be a possible workaround. But I think this should be investigated by VMware support. Maybe the CIM server crashes or some process is "stuck" or busy. It would be great if you could open a ticket at VMware. In our environment we're still running an older version of VMware ESXi, so I cannot reproduce it.

**Comment by ucola** [comment] 2019-04-25 09:38
ok thank you. I dont have permission to submit a support request for my hypervisor licence..

**Comment by Napsty** [comment] 2019-06-05 20:15
In the meantime I got more feedback (directly per e-mail and seen on Nagios Exchange) reporting issues with ESXi 6.7. I am therefore using this ticket as a general "Issues with ESXi 6.7" and renaming it accordingly. Hope you don't mind @ucola ;-)

**Comment by ucola** [comment] 2019-06-06 09:05
if you need some testusers, write me :)

**Comment by Napsty** [comment] 2019-06-06 15:58
@ucola Was that a fresh install of ESXi 6.7 or an upgrade from an older ESXi version?

**Comment by ucola** [comment] 2019-06-06 15:59
Fresh install... I will in the next weeks update it to update2

**Comment by Napsty** [comment] 2019-06-07 18:39
I got more feedback these days. It seems that the Dell Openmanage VIB is the source of this problem and causes timeouts when querying the CIM server.

**Comment by MarcusCaepio** [comment] 2019-06-08 07:40
Hey all,
We have the exact behavior like @ucola , too. But we have SuperMicro Server. I have to connect to the server via ssh and restart sfcbd-watchdog service (don't know the exact name right now, because I am at home).

**Comment by Napsty** [comment] 2019-06-12 13:49
Closing this in favour of #37 . Please post relevant information in #37, for example Server vendor and model, exact ESXi version, installed VIB's.

**Closed by Napsty** 2019-06-12 13:49 UTC
Labels: thirdparty
