### ISSUE TITLE
Connection failures are not properly detected 

### ISSUE THREAD

**Issue by sbraz** [Napsty/check_esxi_hardware#18] opened 2016-12-23 08:45 UTC
Hi,
Because of this [try-except statement](https://github.com/Napsty/check_esxi_hardware/blob/89f9e505c398b382c5af0ba739efe9e6e5ea5cf7/check_esxi_hardware.py#L614),
when there is an issue during the initial connection, the code tries to call pywbem with different arguments and we end up with a non-meaningful exception:
```
TypeError: __init__() got an unexpected keyword argument 'no_verification'
```
I've never been able to test one of these patched pywbem versions but maybe:
* you could just catch SSL connection errors and have another except statement for other connection errors?
* you could look for the keyword in `pywbem.WBEMConnection.__init__.__code__.co_varnames` or using `inspect`?

**Comment by peternewman** [comment] 2017-01-30 12:27
I managed to work around this by doing the following, although I've not tested on a machine running pywbem 0.8.0 or above:
```
if '0.7.' in pywbemversion:
  try:
    conntest = pywbem.WBEMConnection(hosturl, (user,password))
    c = conntest.EnumerateInstances('CIM_Card')
  except pywbem.cim_http.Error, arg:
    #raise
    if ( arg.__str__().find('SSL error: certificate verify failed') >= 0 ):
      verboseoutput("Connection error, disable SSL certification verification (probably patched pywbem)")
      wbemclient = pywbem.WBEMConnection(hosturl, (user,password), no_verification=True)
    else:
      verboseoutput("Other pywbem.cim_http.Error, continue as normal")
      wbemclient = pywbem.WBEMConnection(hosturl, (user,password))
  except:
    verboseoutput("Other connection error, continue as normal")
    wbemclient = pywbem.WBEMConnection(hosturl, (user,password))
  else:
    verboseoutput("Connection worked")
    wbemclient = pywbem.WBEMConnection(hosturl, (user,password))
# pywbem 0.8.0 and later
else:
  wbemclient = pywbem.WBEMConnection(hosturl, (user,password), NS, no_verification=True)
```

Going to open a PR once #21 is in and sorted.

**Comment by pascalsaul** [comment] 2019-07-15 20:40
Nice fix but isn't still included when I just downloaded the latest release?

**Comment by sbraz** [comment] 2019-07-15 21:49
@pascalsaul I guess @peternewman hasn't reated that PR yet.

**Comment by peternewman** [comment] 2019-07-15 22:19
Indeed. I think I forgot by the time the PR got merged. I've opened this:
https://github.com/Napsty/check_esxi_hardware/pull/39

Please can people test it @pascalsaul / @sbraz ?

**Comment by pascalsaul** [comment] 2019-07-15 22:21
I've tested it and that's why I commented it ;) Working on the Dell R740xd like a charm :)

**Comment by peternewman** [comment] 2019-07-15 22:25
> I've tested it and that's why I commented it ;) Working on the Dell R740xd like a charm :)

Can you test the PR please @pascalsaul to make sure I've not made a stupid mistake with the merge and that it still works with the current code.

**Comment by Napsty** [comment] 2020-06-05 13:35
@sbraz Is this actually still relevant? I just installed a new CentOS 7.8, installed pywbem (pywbem-0.7.0-25.20130827svn625.el7.noarch), check_esxi_hardware.py from `sslproto` branch, ESXi 5.0 and it works out of the box:

```
./check_esxi_hardware.py -H 192.168.15.18 -U root -P 123456789 
OK - Server: No Enclosure VMware Virtual Platform s/n: VMware-56 4d 2d 03 ea d4 41 97-89 af 93 78 33 7d 9e 32 System BIOS: 6.00 2017-05-19
```

What are the exact versions to reproduce this?

**Comment by sbraz** [comment] 2020-06-05 13:37
@Napsty I have no idea, it's been a long time since I used that plugin. I now use https://github.com/centreon/centreon-vmware.

**Comment by Napsty** [comment] 2020-06-05 13:39
OK thx for the feedback. I will therefore close this issue and the related PR as meanwhile CentOS 8 is out, too and I am not able to reproduce this issue with a CentOS 7.8.

**Closed by Napsty** 2020-06-05 13:39 UTC
